### ISSUE TITLE
svg 파일 관리 문제

### ISSUE THREAD

**Issue by chanwoo00106** [SLTDV/Choice-FrontEnd#7]
## 개요

svg 파일은 tsx 로 관리하면 build 시에 번들링이 되어서 오히려 더 느려질 수 있기 때문에 public에 관리하는 게 좋습니다

<img width="168" alt="스크린샷 2023-03-20 오후 5 48 43" src="https://user-images.githubusercontent.com/57276315/226289799-535e304d-6210-4f71-a2d4-afacf8618dcc.png">

**Comment by minjekang** [comment]
수정했습니다.
