### ISSUE TITLE
axios 설정에 대한 문제

### ISSUE THREAD

**Issue by chanwoo00106** [SLTDV/Choice-FrontEnd#8]
headers 부분에 있는 Access-Control-Allow-어쩌고 들은 전부 백에서 설정해 주는 값입니다
때문에 전혀 필요없는 코드입니다 cors 문제를 해결하고 싶으면 withcredentials 값만 true로 주면 됩니다

또한 Content-Type 은 axios의 default 값이기 때문에 없어도 됩니다. json이 아닌 다른 걸 통신할 때 사용합니다

base url은 환경변수로 관리하고 있던거 아니었나??
shared 폴더에 config는 도대체 무슨 역할이야?

[mdn 참고 링크](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)

<img width="538" alt="스크린샷 2023-03-20 오후 6 10 34" src="https://user-images.githubusercontent.com/57276315/226294732-98562b09-746e-4305-b5e0-665087fa21b7.png">

**Comment by minjekang** [comment]
process.env.REACT_APP_BASE_URL이 너무 길어서..

**Comment by chanwoo00106** [comment]
> process.env.REACT_APP_BASE_URL이 너무 길어서..

base url 부분 말하는 거지?
base url에 환경 변수를 넣는 이유는 배포 했을 때 편하려고 넣는 거야
만약 테섭이랑 본섭을 같이 배포 한다고 했을 때 이렇게 코드로 박아서 관리하면 많이 불편하잖아

**Comment by minjekang** [comment]
아하 추후에 수정하도록 할게

**Comment by Heeesang** [comment]
정확한 날짜를 명시해주세요.

**Comment by minjekang** [comment]
3/21 
수정하였습니다
